component: http
name: teslamate-proxy

inputs:
  src:
    src: ./
    exclude:
      - .env
  faas:
    runtime: Nodejs16.13
    framework: koa
    name: ${name}
    timeout: 30
    memorySize: 64
  apigw:
    timeout: 60
    # ignoreUpdate: true
    protocols:
      - http
      - https
  region: ap-beijing
stage: prod