name: deploy serverless
 
on: #监听的事件和分支配置
  push:
    branches:
      - main
 
jobs:
  deploy:
    name: deploy serverless
    runs-on: ubuntu-latest
    steps:
      - name: clone local repository
        uses: actions/checkout@v2
      - name: install dependency
        run: npm install
      - name: install serverless-dev
        run: npm install -g @serverless-devs/s
      - name: serverless-dev deploy
        run: s config add --AccessKeyID ${{secrets.ALI_KEY_ID}} --AccessKeySecret ${{secrets.ALI_SECRET_KEY}} -a default -f
      - run: s deploy -y --use-remote
